{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  openai-api-key: {{ .Values.secret.openai_api_key | b64enc | quote }}
  openai-api-base-url: {{ .Values.secret.openai_api_base_url | b64enc | quote }}
{{- end }}
