apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: admin-apps
  labels:
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/version: 2024.6.0
    helm.sh/chart: authentik-2024.6.0
  annotations:
    meta.helm.sh/release-name: authentik
    meta.helm.sh/release-namespace: admin-apps
type: Opaque
data:
  AUTHENTIK_EMAIL__PORT: NTg3
  AUTHENTIK_EMAIL__TIMEOUT: MzA=
  AUTHENTIK_EMAIL__USE_SSL: ZmFsc2U=
  AUTHENTIK_EMAIL__USE_TLS: ZmFsc2U=
  AUTHENTIK_ERROR_REPORTING__ENABLED: ZmFsc2U=
  AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: azhz
  AUTHENTIK_ERROR_REPORTING__SEND_PII: ZmFsc2U=
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN: L2dlb2lwL0dlb0xpdGUyLUFTTi5tbWRi
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP: L2dlb2lwL0dlb0xpdGUyLUNpdHkubW1kYg==
  AUTHENTIK_LOG_LEVEL: aW5mbw==
  AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: Z2hjci5pby9nb2F1dGhlbnRpay8lKHR5cGUpczolKHZlcnNpb24pcw==
  AUTHENTIK_POSTGRESQL__HOST: YXV0aGVudGlrLXBvc3RncmVzcWw=
  AUTHENTIK_POSTGRESQL__NAME: YXV0aGVudGlr
  AUTHENTIK_POSTGRESQL__PORT: NTQzMg==
  AUTHENTIK_POSTGRESQL__USER: YXV0aGVudGlr
  AUTHENTIK_REDIS__HOST: YXV0aGVudGlrLXJlZGlzLW1hc3Rlcg==
  AUTHENTIK_SECRET_KEY: WU91clN0cm9uZ1NlY3JldEtleVdpdGgzMkNoYXJhY3RlcnNNaQ==
