apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-oauth-data
  namespace: admin-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ionos-enterprise-hdd
  resources:
    requests:
      storage: 1Gi