apiVersion: v1
kind: ConfigMap
metadata:
  name: temp-mariadb-config
  namespace: tenant1
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS wordpress;
    GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'%' IDENTIFIED BY '29Qk7LG875j8BAfXJboWhA==';
    FLUSH PRIVILEGES;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-mariadb
  namespace: tenant1
  labels:
    app: temp-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp-mariadb
  template:
    metadata:
      labels:
        app: temp-mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword123"
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wpuser"
        - name: MYSQL_PASSWORD
          value: "29Qk7LG875j8BAfXJboWhA=="
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
      - name: init-script
        configMap:
          name: temp-mariadb-config
---
apiVersion: v1
kind: Service
metadata:
  name: temp-mariadb
  namespace: tenant1
  labels:
    app: temp-mariadb
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: temp-mariadb