{{- if .Values.authentik.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authentik.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secret_key: {{ .Values.authentik.secret.secret_key | b64enc | quote }}
  postgres_password: {{ .Values.authentik.secret.postgres_password | b64enc | quote }}
  postgres_host: {{ .Values.authentik.secret.postgres_host | b64enc | quote }}
  postgres_user: {{ .Values.authentik.secret.postgres_user | b64enc | quote }}
  postgres_name: {{ .Values.authentik.secret.postgres_name | b64enc | quote }}
{{- end }}
