# values.template.yaml for Open WebUI Helm chart

webui:
  extraEnvVars:
    - name: OPENAI_API_BASE_URL
      value: "https://openai.inference.de-txl.ionos.com/v1"
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-api-key
          key: api-key
  ingress:
    enabled: true
    hostname: openwebui.example.com  # Change to your domain
    tls: false
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  persistence:
    enabled: true
    size: 4Gi
    accessModes:
      - ReadWriteOnce
    storageClass: ""  # Set to your storage class if needed 