ollama:
  enabled: false

pipelines:
  enabled: false

extraEnvVars:
  - name: OPENAI_API_BASE_URL
    value: 'https://openai.inference.de-txl.ionos.com/v1'
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: openai-api-key
        key: api-key

ingress:
  enabled: true
  host: openwebui.example.com # Change to actual domain
  tls: false

replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi

persistence:
  enabled: true
  size: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClass: '' # Set to your storage class if needed

service:
  type: LoadBalancer
  port: 80
