ollama:
  enabled: false

pipelines:
  enabled: false

envFrom:
  - secretRef:
      name: openwebui-env-secrets

ingress:
  enabled: true
  host: openwebui.example.com # Change to actual domain
  tls: false

replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi

persistence:
  enabled: true
  size: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClass: '' # Set to your storage class if needed

service:
  type: LoadBalancer
  port: 80
