apiVersion: v1
kind: Secret
metadata:
  name: authentik-env-secrets
  namespace: admin-apps
type: Opaque
data:
  # All values must be base64 encoded.
  # Use 'echo -n "your-value" | base64' to generate them.
  AUTHENTIK_SECRET_KEY: 'REPLACE_ME'
  AUTHENTIK_BOOTSTRAP_PASSWORD: 'REPLACE_ME'
  AUTHENTIK_POSTGRESQL__HOST: 'REPLACE_ME'
  AUTHENTIK_POSTGRESQL__USER: 'REPLACE_ME'
  AUTHENTIK_POSTGRESQL__PASSWORD: 'REPLACE_ME'
  AUTHENTIK_POSTGRESQL__NAME: 'REPLACE_ME'
