redis:
  enabled: true

server:
  service:
    type: LoadBalancer
    annotations: {}
    labels: {}

authentik:
  secret_key: "${AUTHENTIK_SECRET_KEY}"
  postgresql:
    host: "${POSTGRES_HOST}"
    port: 5432
    name: "authentik"
    user: "authentikuser"
    password: "${POSTGRES_PASSWORD}"
  admin_password: "${AUTHENTIK_ADMIN_PASSWORD}" 