redis:
  enabled: true

authentik:
  secret:
    create: false
    name: authentik
  postgresql:
    host: ''
    port: 5432
    name: ''
    user: ''
    password:
      secretKeyRef:
        name: "authentik-env-secrets"
        key: postgres_password

server:
  extraEnvs: []

worker:
  extraEnvs: []
