redis:
  enabled: true

authentik:
  secret_key: "dummy-will-be-overridden-by-env"
  postgresql:
    host: ''
    port: 5432
    name: ''
    user: ''
    password: ''

envFrom:
  - secretRef:
      name: authentik-env-secrets
