{{- if ne (.Values.database.type | default "mariadb") "sqlite" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-credentials" (include "wordpress.fullname" .) }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
---
{{- end }}
{{- if .Values.authentik.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-oidc-credentials" (include "wordpress.fullname" .) }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.authentik.clientSecret | b64enc | quote }}
{{- end }}
