name: Build and Push WordPress and Pipeline Images

on:
  push:
    branches:
      - main # Or your primary branch
    paths:
      - 'docker/wordpress/Dockerfile'
      - 'docker/wordpress/wp-entrypoint.sh'
      - 'docker/wordpress/plugins/**'
      - 'pipelines/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: wp-openwebui.cr.de-fra.ionos.com
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: Build and Push WordPress Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/wordpress
          push: true
          tags: wp-openwebui.cr.de-fra.ionos.com/jubalm/ionos/poc/wordpress:latest,wp-openwebui.cr.de-fra.ionos.com/jubalm/ionos/poc/wordpress:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Pipeline Service Image
        uses: docker/build-push-action@v5
        with:
          context: ./pipelines
          push: true
          tags: wp-openwebui.cr.de-fra.ionos.com/jubalm/ionos/poc/wordpress-oauth-pipeline:latest,wp-openwebui.cr.de-fra.ionos.com/jubalm/ionos/poc/wordpress-oauth-pipeline:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
