name: Terraform Platform

on:
  push:
    paths:
      - 'terraform/platform/**'
      - '.github/workflows/terraform-platform.yml'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/platform init
      - name: Terraform Plan
        run: terraform -chdir=terraform/platform plan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    # environment: platform-approval  # Uncomment and set up this environment in GitHub repo settings for manual approval
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/platform init
      - name: Terraform Apply
        run: terraform -chdir=terraform/platform apply -auto-approve 