name: Terraform Infrastructure

on:
  push:
    paths:
      - 'terraform/infrastructure/**'
      - '.github/workflows/terraform-infrastructure.yml'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/infrastructure init
      - name: Terraform Plan
        run: terraform -chdir=terraform/infrastructure plan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: infrastructure-approval
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/infrastructure init
      - name: Terraform Apply
        run: terraform -chdir=terraform/infrastructure apply -auto-approve 