name: Terraform Tenant

on:
  push:
    paths:
      - 'terraform/tenant/**'
      - '.github/workflows/terraform-tenant.yml'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/tenant init
      - name: Terraform Plan
        run: terraform -chdir=terraform/tenant plan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    # environment: tenant-approval  # Uncomment and set up this environment in GitHub repo settings for manual approval
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/tenant init
      - name: Terraform Apply
        run: terraform -chdir=terraform/tenant apply -auto-approve 