name: Terraform Infrastructure

on:
  push:
    paths:
      - 'terraform/infrastructure/**'
      - '.github/workflows/terraform-infrastructure.yml'

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ionos_token: ${{ secrets.IONOS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/infrastructure init
      - name: Terraform Plan
        run: terraform -chdir=terraform/infrastructure plan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: infrastructure-approval
    env:
      TF_VAR_ionos_token: ${{ secrets.IONOS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=terraform/infrastructure init
      - name: Terraform Apply
        run: terraform -chdir=terraform/infrastructure apply -auto-approve 