name: Terraform Infrastructure

on:
  push:
    paths:
      - 'terraform/infrastructure/**'
      - '.github/workflows/terraform-infrastructure.yml'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Render my-values.yaml
        run: |
          chmod +x charts/authentik/render-values.sh
          ./charts/authentik/render-values.sh
        env:
          AUTHENTIK_SECRET_KEY: ${{ secrets.AUTHENTIK_SECRET_KEY }}
          AUTHENTIK_ADMIN_PASSWORD: ${{ secrets.AUTHENTIK_ADMIN_PASSWORD }}
          IONOS_TOKEN: ${{ secrets.IONOS_TOKEN }}
          # Add any other required env vars here
      - name: Terraform Init
        run: terraform -chdir=terraform/infrastructure init
      - name: Terraform Plan
        run: terraform -chdir=terraform/infrastructure plan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: infrastructure-approval
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Render my-values.yaml
        run: |
          chmod +x charts/authentik/render-values.sh
          ./charts/authentik/render-values.sh
        env:
          AUTHENTIK_SECRET_KEY: ${{ secrets.AUTHENTIK_SECRET_KEY }}
          AUTHENTIK_ADMIN_PASSWORD: ${{ secrets.AUTHENTIK_ADMIN_PASSWORD }}
          IONOS_TOKEN: ${{ secrets.IONOS_TOKEN }}
          # Add any other required env vars here
      - name: Terraform Init
        run: terraform -chdir=terraform/infrastructure init
      - name: Terraform Apply
        run: terraform -chdir=terraform/infrastructure apply -auto-approve 